defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/base:10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # find compatible cache from previous build,
      # it should have same dependencies installed from package.json checksum
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      # run verify and then save cache.
      # this ensures that the Cypress verified status is cached too
      - run: npm run cy:verify
      # save new cache folder if needed
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run types
      # all other test jobs will run AFTER this build job finishes
      # to avoid reinstalling dependencies, we persist the source folder "app"
      # and the Cypress binary to workspace, which is the fastest way
      # for Circle jobs to pass files
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

  test-locally:
    <<: *defaults
    steps:
      # restore application and Cypress binary before running the test command
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run test:record

  4x-electron:
    <<: *defaults
    # tell CircleCI to execute this job on 4 machines simultaneously
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      # runs Cypress test in load balancing (parallel) mode
      # and groups them in Cypress Dashboard under name "4x-electron"
      - run: npm run e2e:record -- --parallel --group $CIRCLE_JOB

  2x-chrome:
    <<: *defaults
    # execute this job on 2 CI machines
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: npm start
          background: true
      - run: npm run e2e:record -- --parallel --group $CIRCLE_JOB --browser chrome

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-locally:
          requires:
            - build
